# Generated by Django 6.0.3 on 2026-04-07 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('leave_type', models.CharField(choices=[('annual', '연차'), ('half_day', '반차'), ('sick', '병가'), ('other', '기타')], max_length=20, verbose_name='휴가종류')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
