# Generated by Django 6.0.3 on 2026-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='사용일수'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='반려 사유'),
        ),
    ]
