# Generated by Django 6.0.3 on 2026-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_leaverequest_days_count_leaverequest_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려'), ('canceled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
