# Generated by Django 6.0.4 on 2026-04-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_reason',
            field=models.TextField(blank=True, verbose_name='휴가 사유'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', '연차'), ('half_day', '반차'), ('paid', '유급'), ('unpaid', '무급'), ('bereavement', '경조'), ('reward', '포상'), ('training', '훈련'), ('other', '기타')], max_length=20, verbose_name='휴가종류'),
        ),
    ]
