# Generated by Django 6.0.3 on 2026-04-07 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('employee_number', models.CharField(max_length=30, unique=True, verbose_name='사번')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('position', models.CharField(max_length=50, verbose_name='직급')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('employment_status', models.CharField(choices=[('active', '재직'), ('leave', '휴직'), ('resigned', '퇴사')], default='active', max_length=20, verbose_name='재직상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('department_change', models.CharField(blank=True, max_length=100, verbose_name='부서변경')),
                ('position_change', models.CharField(blank=True, max_length=50, verbose_name='직급변경')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_records', to='employee.employee')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
