# Generated by Django 6.0.3 on 2026-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('진료부', '진료부'), ('3병동', '3병동'), ('5A병동', '5A병동'), ('5B병동', '5B병동'), ('수술실', '수술실'), ('치료실', '치료실'), ('외래', '외래'), ('상담실', '상담실'), ('간호부', '간호부'), ('간호행정', '간호행정'), ('원무과', '원무과'), ('총무과', '총무과'), ('시설과', '시설과'), ('심사과', '심사과'), ('검진센터', '검진센터'), ('영상의학과', '영상의학과'), ('진단검사의학과', '진단검사의학과'), ('물리치료', '물리치료'), ('운동치료', '운동치료'), ('원내약국', '원내약국'), ('영양과', '영양과')], max_length=100, verbose_name='부서'),
        ),
    ]
