# Generated by Django 6.0.4 on 2026-04-13 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30, verbose_name='사번')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('department', models.CharField(choices=[('진료부', '진료부'), ('3병동', '3병동'), ('5A병동', '5A병동'), ('5B병동', '5B병동'), ('수술실', '수술실'), ('치료실', '치료실'), ('외래', '외래'), ('상담실', '상담실'), ('간호부', '간호부'), ('간호행정', '간호행정'), ('원무과', '원무과'), ('총무과', '총무과'), ('시설과', '시설과'), ('심사과', '심사과'), ('검진센터', '검진센터'), ('영상의학과', '영상의학과'), ('진단검사의학과', '진단검사의학과'), ('물리치료', '물리치료'), ('운동치료', '운동치료'), ('원내약국', '원내약국'), ('영양과', '영양과')], max_length=100, verbose_name='부서')),
                ('position', models.CharField(max_length=50, verbose_name='직급')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호 해시')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_memo', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_signup_requests', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
