# Generated by Django 6.0.4 on 2026-04-22 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_signuprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='최초 로그인 비밀번호 변경 필요'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='액션')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='대상 모델')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='대상 ID')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='대상 표시명')),
                ('detail', models.TextField(blank=True, verbose_name='상세')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록시각')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='행위자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
